### ISSUE TITLE
waves flicker

### ISSUE THREAD

**Issue by joaquingrech** [Moonlit-Games/Ultimate-Water-System#45] opened 2018-01-30 21:28 UTC
so let me explain my problem. I have to create 2 lakes, but let's just go with one right now. I create the water gameobject, set the shader to container, custom meshes and all. Since the lake is pretty large, I have to scale the water game object to 250,1,250

hit play, the water shows but the wave system is all meshed up with lot of flickering. I've tried everything I could think of with no luck.
Also the shoreline instead of white, it's brown. I even tried to copy all settings, with prefabs and all from the Shore demo and i still get a brown shoreline.

here a link to the video, check the wave next to the surface where it's most visible but happens everywhere on the water
https://youtu.be/kFTFbFeRjdU

**Comment by MCPGNZ** [comment] 2018-01-31 10:15
Hi, 

I believe that the first issue is caused by the Custom Mesh set to Plane. This mesh has relatively few vertices, so even after the tesselation, the water is very low-resolution. 

The shore problem: could you give me your Unity version and UWS version and your water setup (defauit/forward/deferred mode)  it will be easier for me to check whats happening.

**Comment by MCPGNZ** [comment] 2018-02-09 15:01
Hi!
Does the suggestions I've provided helped?

**Comment by MCPGNZ** [comment] 2018-02-21 12:11
Closing for now as i do believe that the suggestions provided should resolve the issue. If there are any more problems please feel free to open a new issue.

**Closed by MCPGNZ** 2018-02-21 12:11 UTC
Labels: bug: graphics
