### ISSUE TITLE
Broken OpenGL

### ISSUE THREAD

**Issue by leonidasos** [Moonlit-Games/Ultimate-Water-System#27] opened 2017-11-13 12:21 UTC
OpenGL is broken and it's very important to fix it, beacuse neither Linux nor MacOSX is not working properly with UWS. 
**unity:** 5.6.4f1
**uws version:** 1.0.0b3 
**spec:** AMD RX 560, Intel i5-6400

Set up OpenGL API and run 'Shore' scene: 
Regarding OpenGL errors:
1) compilation error:
![2017-11-10_18h40_38](https://user-images.githubusercontent.com/2396651/32724801-ff65fb70-c872-11e7-85a8-1fd2e1b7043f.png)

2) Water mask over the terrain. Add terrain to 'Shore' scene. This bug disqualifies using OpenGL and UWS. It's very important to fix it. 

Actually it's blocker for us.

![2017-11-13_13h11_52](https://user-images.githubusercontent.com/2396651/32725398-3752eece-c875-11e7-9b9c-cb7a2deb960a.png)

**Comment by MCPGNZ** [comment] 2017-11-17 12:58
I'm closing this Issue because it's a duplicate of #3 
The OpenGl problems are a priority and will be solved in the next iteration.

**Closed by MCPGNZ** 2017-11-17 12:58 UTC
